[38;5;127mlibs[0m/[38;5;172mstardist[0m/[38;5;67m0.9.1[0m
 |
 [0;32mOK[0m
                     [38;5;127mlibs[0m/[38;5;172mstardist[0m/[38;5;67m0.9.1[0m ... UNLOADING --> [0;32mOK[0m
[38;5;127mlibs[0m/[38;5;172mhistomicstk[0m/[38;5;67m1.3.8[0m
 |
 [0;32mOK[0m
                  [38;5;127mlibs[0m/[38;5;172mhistomicstk[0m/[38;5;67m1.3.8[0m ... UNLOADING --> [0;32mOK[0m
[38;5;127mapps[0m/[38;5;172manaconda3[0m/[38;5;67m2023.03[0m/[38;5;68mbin[0m
 |
 [0;32mOK[0m
/opt/gridware/depots/996bcebb/el7/pkg/apps/anaconda3/2023.03/bin/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator SimpleImputer from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/gridware/depots/996bcebb/el7/pkg/apps/anaconda3/2023.03/bin/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator StandardScaler from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/gridware/depots/996bcebb/el7/pkg/apps/anaconda3/2023.03/bin/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator Pipeline from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/gridware/depots/996bcebb/el7/pkg/apps/anaconda3/2023.03/bin/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/gridware/depots/996bcebb/el7/pkg/apps/anaconda3/2023.03/bin/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator OrdinalEncoder from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/gridware/depots/996bcebb/el7/pkg/apps/anaconda3/2023.03/bin/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator ColumnTransformer from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/gridware/depots/996bcebb/el7/pkg/apps/anaconda3/2023.03/bin/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/opt/gridware/depots/996bcebb/el7/pkg/apps/anaconda3/2023.03/bin/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator AdaBoostClassifier from version 1.2.2 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "/users/ad394h/Documents/nuclei_segment/scripts/classify_image.py", line 120, in <module>
    new_label_image = relabel_image(test_class_df)
  File "/users/ad394h/Documents/nuclei_segment/scripts/classify_image.py", line 94, in relabel_image
    label_objects = test_classes.loc[:,'label']
NameError: name 'test_classes' is not defined. Did you mean: 'test_class_df'?
